sudo: false
language: python
# This only controls the version of Python used to run tox, the
# versions used for the tests are handled by tox itself. Python 3.5
# is only installed if we explicitly request it, so we have to use
# it as the base, so that it's available to tox. Python 2.7 and 3.4
# are available in the Travis images by default. See:
# https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-143758799
python: "3.5"
env:
    # Keep in sync with tox.ini.

    - TOX_ENV=docs

    - TOX_ENV=py27-django1.8-drf3.4
    - TOX_ENV=py27-django1.8-drf3.5
    - TOX_ENV=py27-django1.9-drf3.4
    - TOX_ENV=py27-django1.9-drf3.5
    - TOX_ENV=py27-django1.10-drf3.4
    - TOX_ENV=py27-django1.10-drf3.5
    - TOX_ENV=py27-django1.11-drf3.5

    - TOX_ENV=py34-django1.8-drf3.4
    - TOX_ENV=py34-django1.8-drf3.5
    - TOX_ENV=py34-django1.9-drf3.4
    - TOX_ENV=py34-django1.9-drf3.5
    - TOX_ENV=py34-django1.10-drf3.4
    - TOX_ENV=py34-django1.10-drf3.5
    - TOX_ENV=py34-django1.11-drf3.5

    - TOX_ENV=py35-django1.8-drf3.4
    - TOX_ENV=py35-django1.8-drf3.5
    - TOX_ENV=py35-django1.9-drf3.4
    - TOX_ENV=py35-django1.9-drf3.5
    - TOX_ENV=py35-django1.10-drf3.4
    - TOX_ENV=py35-django1.10-drf3.5
    - TOX_ENV=py35-django1.11-drf3.5
    - TOX_ENV=py35-djangomaster-drf3.5
matrix:
  include:
    # Python 3.6 has to be specified explicitly since it's not installed by default.
    - python: 3.6
      env: TOX_ENV=py36-django1.11-drf3.5
    - python: 3.6
      env: TOX_ENV=py36-djangomaster-drf3.5
  allow_failures:
    # Django master is allowed to fail.
    - env: TOX_ENV=py35-djangomaster-drf3.5
    - python: 3.6
      env: TOX_ENV=py36-djangomaster-drf3.5
  fast_finish: true
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
